#ifndef SHAREDELEMENTS_GLOBAL_H
#define SHAREDELEMENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHAREDELEMENTS_LIBRARY)
#  define SHAREDELEMENTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHAREDELEMENTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHAREDELEMENTS_GLOBAL_H
