#ifndef HOUSEDATAHANDLER_GLOBAL_H
#define HOUSEDATAHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HOUSEDATAHANDLER_LIBRARY)
#  define HOUSEDATAHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HOUSEDATAHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HOUSEDATAHANDLER_GLOBAL_H
