#ifndef HOMESERVER_GLOBAL_H
#define HOMESERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HOMESERVER_LIBRARY)
#  define HOMESERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HOMESERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HOMESERVER_GLOBAL_H
