#ifndef HOMENETWORK_GLOBAL_H
#define HOMENETWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HOMENETWORK_LIBRARY)
#  define HOMENETWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HOMENETWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HOMENETWORK_GLOBAL_H
